path_planning:
  planner: RRT*  # Options: RRT, RRT*
  dimensions: 2   # Options: 2 and 3
  domain: 50    # The length of domain for each dimension. 2 dimension: (50, 50) and 3 dimension (50, 50, 50)
  k: 1000
  step: 5
  use_obstacle: false
  should_visualize: true
  frame_update: 0.5
